### ISSUE TITLE
Support for new API

### ISSUE THREAD

**Issue by Elegant996** [borchero/switchboard#111]
With the release of traefik v2.10, `traefik.containo.us` API has been deprecated. Could we build with the latest version of traefik to obtain support for the new `traefik.io` API? Thanks!

**Comment by borchero** [comment]
Makes sense, care to take a stab at it in a PR? :smile:

**Comment by Elegant996** [comment]
Got it working on my end but it may take more work to make this a real PR. It looks like we'd have to add both crds to switchboard. The quick and dirty I made only converts everything to the new one. The issue is importing traefik:

```
traefik "github.com/traefik/traefik/v2/pkg/provider/kubernetes/crd/traefik/v1alpha1"
```

To support both, we would have to introduce another one like so:

```
traefikio "github.com/traefik/traefik/v2/pkg/provider/kubernetes/crd/traefikio/v1alpha1"
```

Afterwards, we could observe both. May get around to this would take more testing than just the quick remaining on I did on the PR to support traefik v2.10.1.

**Comment by borchero** [comment]
I've never worked with an operator supporting two versions of a CRD so I need to investigate this a little. Will work on it soonish 😬

**Comment by AlexGodbehere** [comment]
@borchero, to confirm - this is still not implemented? Would explain why none of my IngressRoutes are being picked up 😅

**Comment by borchero** [comment]
Not implemented yet! Feel free to open a PR, I still didn't have time for it, unfortunately

**Comment by mya-crabnebula** [comment]
@borchero I've pushed up a patch that I believe addresses this. I haven't ever seen an operator or controller that works with multiple CRD definitions (unless it's fully self contained)

**Comment by cuseinovic** [comment]
Hello guys, 
I encountered the same problem here. Do you have some news about this PR or this topic ? 

Thanks
