### ISSUE TITLE
Allow setting default `Certificate` specs

### ISSUE THREAD

**Issue by DerEnderKeks** [borchero/switchboard#13]
It would be nice if it was possible to set custom default specs for the `Certificate` CRs that switchboard creates.
Specifically I'd like to set the [`privateKey`](https://cert-manager.io/docs/reference/api-docs/#cert-manager.io/v1.CertificatePrivateKey) specs.

Btw.: Thanks for this great little project!

**Comment by borchero** [comment]
Do I understand correctly that this is something that you'd like to set globally for the cert-manager integration, i.e. for all processed ingress routes?

**Comment by DerEnderKeks** [comment]
Yes, exactly. Setting these specs per ingress via annotations would also be interesting, but a global default is more important to me at the moment.

**Comment by borchero** [comment]
Sorry this took so long! The idea is to allow the `cert-manager` integration to specify a `certificateTemplate` (just like you have `podTemplate` for a deployment, for example) instead of merely specifying the issuer. Let me know if this satisfies your requirement!

**Comment by DerEnderKeks** [comment]
That sounds like a perfectly fine solution, thanks!
