### ISSUE TITLE
Docker image fails to pull

### ISSUE THREAD

**Issue by 0x0013** [borchero/switchboard#22]
Hi!

The docker image of switchboard fails to pull:

```
❯ docker pull ghcr.io/borchero/switchboard:0.5.0
0.5.0: Pulling from borchero/switchboard
manifest unknown
```

**Comment by borchero** [comment]
Yeah I messed something up, sorry... apparently GHCR keeps tags around even if the underlying manifest is deleted.

**Comment by borchero** [comment]
Will re-upload in a few minutes

**Comment by borchero** [comment]
Should be fixed, let me know!

**Comment by Benjvfr** [comment]
Hello,

Only the image with tag 0.5 is pulling.
`docker pull ghcr.io/borchero/switchboard:0.5
0.5: Pulling from borchero/switchboard
9880fb5de7c7: Pull complete
86fdc3b98511: Pull complete
Digest: sha256:c9e631476d459cd98dc3f2acb2d44addb3fc4ea067570ea3034e47f05723e8e2
Status: Downloaded newer image for ghcr.io/borchero/switchboard:0.5
ghcr.io/borchero/switchboard:0.5`

When I use the Helm Chart, that tried to pull image 0.3 (and I also tried 0.4), the manifest is unkown :
`docker pull ghcr.io/borchero/switchboard:0.4
0.4: Pulling from borchero/switchboard
manifest unknown`

**Comment by borchero** [comment]
Should be solved, can you check again?

**Comment by Benjvfr** [comment]
It's working now ! 👍 
Thanks.

**Comment by borchero** [comment]
Great! I'll close this as all issues from 0.3 onwards should be resolved. Sorry for the hickup, won't happen again 😅
