### ISSUE TITLE
disable cert-manager `Certificate` creation

### ISSUE THREAD

**Issue by schmurfy** [borchero/switchboard#3]
Really nice to see a solution to a problem we have since ages ago but we currently already create the certificate in our manifests, it would be nice if there was a way to only create the Resource for external-dns.

I have looked a bit and have no see any evidence this is currently possible.

**Comment by borchero** [comment]
That's a good point. Do you think it makes more sense to disable the generation globally (i.e. Switchboard should not generate certificates for all ingress routes it processes) or would you rather set an annotation? One could also think of having a global default and overwrite this default with annotations in the ingress routes.

**Comment by mamiu** [comment]
It would be great to have a ConfigMap that holds all Switchboard settings. And in there the user has the option to turn on or turn off certain features. E.g. `enableCertManagerIntegration` which would be `true` by default or `disableCertManagerIntegration` which would be `false` by default (or something similar to that).
And the same for ExternalDNS and other future integrations or configuration options.

**Comment by borchero** [comment]
@mamiu following your idea with enabling Switchboard to generalize for arbitrary integrations, I refactored the codebase another time (see #4). You can freely enable and disable individual integrations now. I'll also update the Helm chart soon ;)

**Comment by mamiu** [comment]
@borchero Wow, you're a genius! I think, now you've an amazing foundation for future changes, features, addons, etc. Thanks for doing all the work!

**Comment by borchero** [comment]
Switchboard Helm Chart v0.2.0 is now also released and supports this feature :)

**Comment by schmurfy** [comment]
Thanks, that's awesome :)
Sorry for radio silence I did not find the time to get back to this thread :/
