### ISSUE TITLE
Support multiple Hosts

### ISSUE THREAD

**Issue by Elegant996** [borchero/switchboard#30]
Hi! Just installed this chart but realized that it doesn't support multiple hostnames. Example would be:
```
routes:
- match: Host(`myhost.example.com`) || Host(`myhost`)
  kind: Rule
```
Or:
```
routes:
- match: Host(`myhost.example.com, `myhost`)
  kind: Rule
```
Could we have support added for multiple hosts per `IngressRoute`?

Thanks!

**Comment by 0x0013** [comment]
Not the maintainer, but I think it already supports multiple hosts, but probably just the second non-fqdn domain is not being picked up by the regex: https://github.com/borchero/switchboard/blob/main/internal/switchboard/hosts.go#L11
It expects at least one dot `.` and the second part of at least 2 symbols

**Comment by Elegant996** [comment]
Ah! Then in my case, I'm also looking for support for shorthand domain names...

**Comment by borchero** [comment]
@Elegant996 thanks for raising this! This should definitely be supported.
