### ISSUE TITLE
Cannot deploy 0.5.6 app version

### ISSUE THREAD

**Issue by vandot** [borchero/switchboard#76]
Trying new chart (0.5.6) with new app (0.5.6) doesn't work for some reason, `/healthz` and `/readyz` both fail
```
Warning  Unhealthy  90s (x13 over 3m10s)  kubelet            Readiness probe failed: Get "http://172.20.4.12:8081/readyz": dial tcp 172.20.4.12:8081: connect: connection refused                                                                                        │
Warning  Unhealthy  90s (x4 over 3m)      kubelet            Liveness probe failed: Get "http://172.20.4.12:8081/healthz": dial tcp 172.20.4.12:8081: connect: connection refused
```
Installing new chart with old app version `0.5.5` works

**Comment by borchero** [comment]
I'll have a look!

**Comment by joelgriffiths** [comment]
I had the exact same problem. I thought I had configured something incorrectly.

Thanks for posting the solution. Downgraded to 0.5.5, and everything started working.

**Comment by borchero** [comment]
`v0.5.7` should fix this!

**Comment by vandot** [comment]
@borchero it's fixed
